NSWCC-805: Update Java version in generated Dockerfile to match expected version

diff --git a/src/main/resources/Dockerfile.j2 b/src/main/resources/Dockerfile.j2
--- a/src/main/resources/Dockerfile.j2
+++ b/src/main/resources/Dockerfile.j2
@@ -6,6 +6,12 @@
  # www.brightsparklabs.com
  ##
 
+# ------------------------------------------------------------------------------
+# CONSTANTS
+# ------------------------------------------------------------------------------
+
+ARG JAVA_OCI_IMAGE=eclipse-temurin:25.0.3_9-jdk-jammy
+
 # -----------------------------------------
 # BUILD STAGE: GENERATE PDF FILES
 # -----------------------------------------
@@ -18,28 +24,27 @@
 #
 #   docker build -t docs -f <GENERATED_DOCKER_FILE> --target builder-pdf .
 
-FROM eclipse-temurin:21.0.9_10-jdk-jammy AS builder-pdf
+FROM ${JAVA_OCI_IMAGE} AS builder-pdf
 
 RUN apt update
+RUN apt install -y curl
 # Allow gradle-docs plugin to read git details on files.
 RUN apt install -y git
-
 # Allow asciidoctor-diagram to render plantuml (dot) diagrams.
 RUN apt install -y graphviz
 
 # Allow asciidoctor-diagram to render Vega diagrams.
-# nvm needs an interactive shell: https://stackoverflow.com/a/60137919
-SHELL ["/bin/bash", "--login", "-i", "-c"]
 RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
-RUN source ~/.bashrc
-RUN nvm install lts/iron
-RUN npm install -g vega-cli
+# nvm needs to run in an interactive bash shell so it sources ~/.bashrc.
+# See: https://stackoverflow.com/a/60137919
+RUN bash -i -c "nvm install lts/iron && npm install -g vega-cli"
 
 # Get gradle distribution (done separately so Docker caches layer)
 WORKDIR /src
 COPY build.gradle settings.gradle gradlew ./
 COPY gradle ./gradle/
-RUN ./gradlew build || true # force sucess as build is expected to fail due to no sources
+RUN ./gradlew build || true # Force success as build is expected to fail due to no .git or sources.
+RUN echo "\n^^^ SAFE TO IGNORE ABOVE ERROR - refer to comment about forcing 'true'\n"
 
 COPY .git ./.git
 COPY src ./src
@@ -62,19 +67,21 @@ COPY --from=builder-pdf /src/build/docs/asciidoc .
 # BUILD STAGE: GENERATE ASCIIDOC FILES
 # -----------------------------------------
 
-FROM eclipse-temurin:21.0.9_10-jdk-alpine AS builder-java
+FROM ${JAVA_OCI_IMAGE} AS builder-java
 
 # Directory where to build the image from.
 ARG BUILD_IMAGES_DIR="{{ config.buildImagesDir }}"
 
 # Allow gradle-docs plugin to read git details on files.
-RUN apk add git
+RUN apt update
+RUN apt install -y git
 
 # Get gradle distribution (done separately so Docker caches layer)
 WORKDIR /src
 COPY build.gradle settings.gradle gradlew ./
 COPY gradle ./gradle
-RUN ./gradlew build || true # force sucess as build is expected to fail due to no sources
+RUN ./gradlew build || true # Force success as build is expected to fail due to no .git or sources.
+RUN echo "\n^^^ SAFE TO IGNORE ABOVE ERROR - refer to comment about forcing 'true'\n"
 
 COPY .git ./.git
 COPY src ./src
